version: "3.7"
services:

  nginx:
    depends_on:
      - mariadb
      - wordpress
    build: ./requirements/nginx
    image: nginx
    volumes:
      - wp-data:/var/www/wordpress/
    ports:
      - "443:443"
    networks:
      - backend
    env_file:
      - .env
    restart: always

  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3306"
    networks:
      - backend
    env_file:
      - .env
    restart: always

  wordpress:
    depends_on:
      - mariadb
    build: ./requirements/wordpress
    image: wordpress
    volumes:
      - wp-data:/var/www/wordpress/
    ports:
      - "9000"
    networks:
      - backend
    env_file:
      - .env
    restart: always

networks:
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local
    driver_opts:
      type: none
      device: "/home/imannouc/data/db-data"
      o: bind
  wp-data:
    driver: local
    driver_opts:
      type: none
      device: "/home/imannouc/data/wp-data"
      o: bind
